### ISSUE TITLE
Nil pointer problem with saving languages

### ISSUE THREAD

**Issue by lmullen** [lmullen/cchc#47]
```
cchc-language-detector-2  | panic: runtime error: invalid memory address or nil pointer dereference
cchc-language-detector-2  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7a8b6b]
cchc-language-detector-2  |
cchc-language-detector-2  | goroutine 2738 [running]:
cchc-language-detector-2  | github.com/lmullen/cchc/common/results.(*Repo).SaveLanguages(0xc00000e1f0, 0x6856968, 0xc081a43b60, 0xb24667dedf490d90, 0xd9a48a9bc8032496, 0xc0117f1920, 0x23, 0xc000800db0, 0x0, 0x0)
cchc-language-detector-2  | 	/cchc/common/results/repository_pgx.go:47 +0xab
cchc-language-detector-2  | main.processDocument(0xc0b2a96d00, 0x0, 0x0)
cchc-language-detector-2  | 	/cchc/language-detector/process-document.go:59 +0x4a3
cchc-language-detector-2  | main.processJobs(0x68568f8, 0xc000215300, 0xc000024510)
cchc-language-detector-2  | 	/cchc/language-detector/process-jobs.go:40 +0x47b
cchc-language-detector-2  | created by main.main
cchc-language-detector-2  | 	/cchc/language-detector/main.go:53 +0x30a
cchc-language-detector-2  | panic: runtime error: invalid memory address or nil pointer dereference
cchc-language-detector-2  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7a8b6b]
cchc-language-detector-2  |
cchc-language-detector-2  | goroutine 311 [running]:
cchc-language-detector-2  | github.com/lmullen/cchc/common/results.(*Repo).SaveLanguages(0xc000386018, 0x6856968, 0xc0b8b0bc80, 0xa84a30d203c74c0b, 0x2dd41ab07451f781, 0xc00093b5f0, 0x23, 0xc0014a3110, 0x0, 0x0)
cchc-language-detector-2  | 	/cchc/common/results/repository_pgx.go:47 +0xab
cchc-language-detector-2  | main.processDocument(0xc059645180, 0x0, 0x0)
cchc-language-detector-2  | 	/cchc/language-detector/process-document.go:59 +0x4a3
cchc-language-detector-2  | main.processJobs(0x68568f8, 0xc00027d300, 0xc000398010)
cchc-language-detector-2  | 	/cchc/language-detector/process-jobs.go:40 +0x47b
cchc-language-detector-2  | created by main.main
cchc-language-detector-2  | 	/cchc/language-detector/main.go:53 +0x30a
```

**Comment by lmullen** [comment]
This appears to have been successfully fixed by the commit above. Will re-open if it is still a problem.
